BTL/Controllers/Admin/SanPhamAdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BTL.Models;
using PagedList;

namespace BTL.Controllers.Admin
{
    public class SanPhamAdminController : Controller
    {
        private ShopDienThoaiContext db = new ShopDienThoaiContext();

        // GET: SanPhams
        public ActionResult Index(int? page)
        {

            var sanPhams = db.SanPhams.Include(s => s.LoaiSanPham);
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(sanPhams.OrderBy(h => h.MaSanPham).ToPagedList(pageNumber, pageSize));
        }

        // GET: SanPhams/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            var list = from smd in db.SanPham_MauSac_DungLuong
                       join d in db.DungLuongs on smd.ID_DungLuong equals d.ID_DungLuong
                       join m in db.MauSacs on smd.ID_MauSac equals m.ID_MauSac
                       where smd.MaSanPham == sanPham.MaSanPham
                       select new SanPhamKichThuocMauSacDTO
                       {
                           MaSanPham = smd.MaSanPham,
                           ID_DungLuong = d.ID_DungLuong,
                           ID_MauSac = m.ID_MauSac,
                           Gia = (int)smd.Gia,
                           SoLuongCon = (int)smd.SoLuongCon,
                           KichThuoc = (int)d.KichThuoc,
                           TenMau = m.TenMau 
                       };
            ViewBag.DanhSachDungLuongMauSac = list.ToList();
            return View(sanPham);
        }

        // GET: SanPhams/Create
        public ActionResult Create()
        {
            ViewBag.MaLoaiSanPham = new SelectList(db.LoaiSanPhams, "MaLoaiSanPham", "TenLoaiSanPham");
            ViewBag.ID_DungLuong = new SelectList(db.DungLuongs, "ID_DungLuong", "KichThuoc");
            ViewBag.ID_MauSac = new SelectList(db.MauSacs, "ID_MauSac", "TenMau");
            return View();
        }

        // POST: SanPhams/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaSanPham,TenSanPham,HinhAnh,MoTa,NgayTao,NgayCapNhat,SanPhamMoi,NoiBat,MaLoaiSanPham")] SanPham sanPham,
            [Bind(Include = "ID_DungLuong, ID_MauSac, Gia, SoLuongCon")] SanPham_MauSac_DungLuong smd)
        {
            if (smd.Gia == null || smd.SoLuongCon == null)
            {
                ViewBag.Error = "Bạn phải điền cả giá và số lượng";
                ViewBag.MaLoaiSanPham = new SelectList(db.LoaiSanPhams, "MaLoaiSanPham", "TenLoaiSanPham", sanPham.MaLoaiSanPham);
                ViewBag.ID_DungLuong = new SelectList(db.DungLuongs, "ID_DungLuong", "KichThuoc");
                ViewBag.ID_MauSac = new SelectList(db.MauSacs, "ID_MauSac", "TenMau");
                return View(sanPham);
            }
            try
            {
                if (ModelState.IsValid)
                {
                    sanPham.HinhAnh = "";
                    var f = Request.Files["ImageFile"];
                    if (f != null && f.ContentLength > 0)
                    {
                        string FileName = System.IO.Path.GetFileName(f.FileName);
                        string UploadFile = Server.MapPath("~/wwwroot/images/sanpham/" + FileName);
                        f.SaveAs(UploadFile);
                        sanPham.HinhAnh = FileName;
                    }
                    sanPham.NgayTao = DateTime.Now;
                    sanPham.NgayCapNhat = DateTime.Now;
                    db.SanPhams.Add(sanPham);
                    db.SaveChanges();

                    smd.MaSanPham = sanPham.MaSanPham;

                    db.SanPham_MauSac_DungLuong.Add(smd);
                    db.SaveChanges();

                }
                return RedirectToAction("Index");

            }
            catch (Exception ex)
            {
                ViewBag.Error = "Lỗi không tạo mới được." + ex.Message;
                ViewBag.MaLoaiSanPham = new SelectList(db.LoaiSanPhams, "MaLoaiSanPham", "TenLoaiSanPham", sanPham.MaLoaiSanPham);
                ViewBag.ID_DungLuong = new SelectList(db.DungLuongs, "ID_DungLuong", "KichThuoc");
                ViewBag.ID_MauSac = new SelectList(db.MauSacs, "ID_MauSac", "TenMau");
                return View(sanPham);
            }
        }

        // GET: SanPhams/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaLoaiSanPham = new SelectList(db.LoaiSanPhams, "MaLoaiSanPham", "TenLoaiSanPham", sanPham.MaLoaiSanPham);
            ViewBag.ID_DungLuong = new SelectList(db.DungLuongs, "ID_DungLuong", "KichThuoc");
            ViewBag.ID_MauSac = new SelectList(db.MauSacs, "ID_MauSac", "TenMau");
            return View(sanPham);
        }

        // POST: SanPhams/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaSanPham,TenSanPham,HinhAnh,MoTa,NgayTao,NgayCapNhat,SanPhamMoi,NoiBat,MaLoaiSanPham")] SanPham sanPham,
            [Bind(Include = "ID_DungLuong, ID_MauSac, Gia, SoLuongCon")] SanPham_MauSac_DungLuong smd)
        {
            if (smd.Gia == null || smd.SoLuongCon == null)
            {
                ViewBag.Error = "Bạn phải điền cả giá và số lượng";
                ViewBag.MaLoaiSanPham = new SelectList(db.LoaiSanPhams, "MaLoaiSanPham", "TenLoaiSanPham", sanPham.MaLoaiSanPham);
                ViewBag.ID_DungLuong = new SelectList(db.DungLuongs, "ID_DungLuong", "KichThuoc");
                ViewBag.ID_MauSac = new SelectList(db.MauSacs, "ID_MauSac", "TenMau");
                return View(sanPham);
            }
            try
            {
                if (ModelState.IsValid)
                {
                    SanPham sp = db.SanPhams.Where(s => s.MaSanPham == sanPham.MaSanPham).FirstOrDefault();
                    var f = Request.Files["ImageFile"];
                    if (f != null && f.ContentLength > 0)
                    {
                        string FileName = System.IO.Path.GetFileName(f.FileName);
                        string UploadFile = Server.MapPath("~/wwwroot/images/sanpham/" + FileName);
                        f.SaveAs(UploadFile);
                        sp.HinhAnh = FileName;
                    }

                    sp.NgayCapNhat = DateTime.Now;
                    sp.TenSanPham = sanPham.TenSanPham;
                    sp.MoTa = sanPham.MoTa;
                    sp.SanPhamMoi = sanPham.SanPhamMoi;
                    sp.NoiBat = sanPham.NoiBat;
                    sp.MaLoaiSanPham = sanPham.MaLoaiSanPham;
                    //db.Entry(sanPham).State = EntityState.Modified;
                    db.SaveChanges();

                    smd.MaSanPham = sanPham.MaSanPham;

                    bool check = db.SanPham_MauSac_DungLuong.Any(s => s.MaSanPham == smd.MaSanPham &&  s.ID_DungLuong == smd.ID_DungLuong && s.ID_MauSac == smd.ID_MauSac);

                    if(check)
                    {
                        var SMD = db.SanPham_MauSac_DungLuong.Where(s => s.MaSanPham == smd.MaSanPham && s.ID_DungLuong == smd.ID_DungLuong && s.ID_MauSac == smd.ID_MauSac).FirstOrDefault();
                        SMD.Gia = smd.Gia;
                        SMD.SoLuongCon = smd.SoLuongCon;

                        db.SaveChanges();
                    }
                    else
                    {
                        db.SanPham_MauSac_DungLuong.Add(smd);
                        db.SaveChanges();
                    }

                }
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Error = "Lỗi không sửa được" + ex.Message;
                ViewBag.MaLoaiSanPham = new SelectList(db.LoaiSanPhams, "MaLoaiSanPham", "TenLoaiSanPham", sanPham.MaLoaiSanPham);
                ViewBag.ID_DungLuong = new SelectList(db.DungLuongs, "ID_DungLuong", "KichThuoc");
                ViewBag.ID_MauSac = new SelectList(db.MauSacs, "ID_MauSac", "TenMau");
                return View(sanPham);
            }


        }

        // GET: SanPhams/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            return View(sanPham);
        }

        // POST: SanPhams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SanPham sanPham = db.SanPhams.Find(id);
            try
            {

                db.SanPhams.Remove(sanPham);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {

BTL/Views/SanPhamAdmin/Create.cshtml
@model BTL.Models.SanPham

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@using (Html.BeginForm("Create", "SanPhamAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <div>Tên sản phẩm</div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenSanPham, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenSanPham, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div>Hình ảnh</div>
        <div class="col-md-10">
            <img id="output" class="img-rounded" alt="Ảnh" width="180" height="200" src="~/wwwroot/images/261324070_4347523358690584_3346044899357033616_n.png" />
            <p><label for="ufile" style="cursor:pointer;">Chọn File Ảnh</label></p>
            <input name="ImageFile" id="ufile" type="file" style="display:none" onchange="loadFile(event)" />
        </div>
    </div>

    <div class="form-group">
        <div>Mô tả</div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div>Sản phẩm mới</div>
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.SanPhamMoi)
                @Html.ValidationMessageFor(model => model.SanPhamMoi, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div>Sản phẩm nổi bật</div>
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.NoiBat)
                @Html.ValidationMessageFor(model => model.NoiBat, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div>Mã loại sản phẩm</div>
        <div class="col-md-10">
            @Html.DropDownList("MaLoaiSanPham", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.MaLoaiSanPham, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div>Dung lượng</div>
        <div class="col-md-10">
            @Html.DropDownList("ID_DungLuong", null, htmlAttributes: new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        <div>Màu sắc</div>
        <div class="col-md-10">
            @Html.DropDownList("ID_MauSac", null, htmlAttributes: new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        <div>Giá</div>
        <div class="col-md-10">
            @Html.TextBox("Gia", null, htmlAttributes: new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        <div>Số lượng</div>
        <div class="col-md-10">
            @Html.TextBox("SoLuongCon", null, htmlAttributes: new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" style="border-radius:8px" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Quay lại", "Index")
</div>
@if (ViewBag.Error != null)
{
    <br />
    <div class="alert alert-danger" role="alert">@ViewBag.Error</div>
}

<script>
    var loadFile = function (event) {
        var image = document.getElementById('output');
        image.src = URL.createObjectURL(event.target.files[0]);
    }

</script>

BTL/Views/SanPhamAdmin/Delete.cshtml
@model BTL.Models.SanPham

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    var ImagePath = "~/wwwroot/images/sanpham/" + Model.HinhAnh;
}

<h2>Delete</h2>

<h3>Bạn có chắc muốn xóa?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Tên loại sản phẩm
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiSanPham.TenLoaiSanPham)
        </dd>

        <dt>
            Tên sản phẩm
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenSanPham)
        </dd>

        <dt>
            Hình ảnh
        </dt>

        <dd>
            <img id="output" class="img-rounded" alt="Ảnh" width="180" height="200" src="@Url.Content(ImagePath)" /><br />
            @Html.DisplayFor(model => model.HinhAnh)
        </dd>

        <dt>
           Mô tả
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MoTa)
        </dd>

        <dt>
            Ngày tạo
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayTao)
        </dd>

        <dt>
           Ngày cập nhập
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayCapNhat)
        </dd>

        <dt>
            Sản phẩm mới
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SanPhamMoi)
        </dd>

        <dt>
            Sản phẩm nổi bật
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NoiBat)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" style="border-radius:8px" /> |
            @Html.ActionLink("Quay lại", "Index")
        </div>
    }
</div>

BTL/Views/SanPhamAdmin/Details.cshtml
@model BTL.Models.SanPham
@using BTL.Models

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    var ImagePath = "~/wwwroot/images/sanpham/" + Model.HinhAnh;
}

@{ 
    var listSMD = ViewBag.DanhSachDungLuongMauSac as List<SanPhamKichThuocMauSacDTO>;
}



<div>
    <h4>Chi tiết sản phẩm</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Tên loại sản phẩm
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiSanPham.TenLoaiSanPham)
        </dd>

        <dt>
            Tên sản phẩm
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenSanPham)
        </dd>

        <dt>
            Hình ảnh
        </dt>

        <dd>
            <img id="output" class="img-rounded" alt="Ảnh" width="180" height="200" src="@Url.Content(ImagePath)" /><br />
            @Html.DisplayFor(model => model.HinhAnh)
        </dd>

        <dt>
            Mô tả
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MoTa)
        </dd>

        <dt>
            Ngày tạo
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayTao)
        </dd>

        <dt>
            Ngày cập nhập
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayCapNhat)
        </dd>

        <dt>
            Sản phẩm mới
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SanPhamMoi)
        </dd>

        <dt>
            Sản phẩm nổi bật
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NoiBat)
        </dd>

        <dt>
            Danh sách dung lượng - màu sắc
        </dt>

        <dd>

            <table class="table">
                <tr style="border:1px">
                    <th>
                        Kích thước
                    </th>
                    <th>
                        Tên màu
                    </th>
                    <th>
                        Giá
                    </th>
                    <th>
                        Số lượng còn
                    </th>
                </tr>

                @foreach (var item in listSMD)
                {
                    <tr style="border:1px">
                        <td>
                            @item.KichThuoc
                        </td>
                        <td>
                            @item.TenMau
                        </td>
                        <td>
                            @item.Gia.ToString("0,0") VND
                        </td>
                        <td>
                            @item.SoLuongCon
                        </td>
                       
                    </tr>
                }
            </table>      
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Sửa", "Edit", new { id = Model.MaSanPham }, htmlAttributes: new { @class = "btn btn-info btn-sm" })
    @Html.ActionLink("Quay lại", "Index", null, htmlAttributes: new { @class = "btn btn-info btn-sm" })
</p>

BTL/Views/SanPhamAdmin/Edit.cshtml
@model BTL.Models.SanPham

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";

    var ImagePath = "~/wwwroot/images/sanpham/" + Model.HinhAnh;
}

@using (Html.BeginForm("Edit", "SanPhamAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.MaSanPham)

    <div class="form-group">
        <div>Tên sản phẩm</div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenSanPham, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenSanPham, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div>Hình ảnh</div>
        <div class="col-md-10">
            <img id="output" class="img-rounded" alt="Ảnh" width="180" height="200" src="@Url.Content(ImagePath)" />
            <p><label for="ufile" style="cursor:pointer" ;>Chọn File Ảnh</label></p>
            <input name="ImageFile" id="ufile" type="file" style="display:none" onchange="loadFile(event)" />
        </div>
    </div>

    <div class="form-group">
        <div>Mô tả</div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div>Sản phẩm mới</div>
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.SanPhamMoi)
                @Html.ValidationMessageFor(model => model.SanPhamMoi, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div>Sản phẩm nổi bật</div>
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.NoiBat)
                @Html.ValidationMessageFor(model => model.NoiBat, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div>Mã Loại sản phẩm</div>
        <div class="col-md-10">
            @Html.DropDownList("MaLoaiSanPham", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.MaLoaiSanPham, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div>Dung lượng</div>
        <div class="col-md-10">
            @Html.DropDownList("ID_DungLuong", null, htmlAttributes: new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        <div>Màu sắc</div>
        <div class="col-md-10">
            @Html.DropDownList("ID_MauSac", null, htmlAttributes: new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        <div>Giá</div>
        <div class="col-md-10">
            @Html.TextBox("Gia", null, htmlAttributes: new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        <div>Số lượng</div>
        <div class="col-md-10">
            @Html.TextBox("SoLuongCon", null, htmlAttributes: new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" style="border-radius:8px" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Quay lại", "Index")
</div>
@if (ViewBag.Error != null)
{
    <br />
    <div class="alert alert-danger" role="alert">@ViewBag.Error</div>
}
<script>
    var loadFile = function (event) {
        var image = document.getElementById('output');
        image.src = URL.createObjectURL(event.target.files[0]);
    };

</script>

BTL/Views/SanPhamAdmin/Index.cshtml
@model PagedList.IPagedList<BTL.Models.SanPham>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

<h2 style="text-align:center">Quản lý sản phẩm</h2>

<p>
    @Html.ActionLink("Tạo Mới", "Create", null, htmlAttributes: new { @class = "btn btn-success btn-sm" })
</p>
<table class="table">
    <tr style="border:1px">
        <th>
            Tên loại sản phẩm
        </th>
        <th>
            Tên sản phẩm
        </th>
        <th>
            Hình ảnh
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr style="border:1px">
            <td>
                @Html.DisplayFor(modelItem => item.LoaiSanPham.TenLoaiSanPham)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TenSanPham)
            </td>
            <td>
                @{
                    string ImagePath = "~/wwwroot/images/sanpham/" + item.HinhAnh;
                }
                <img src="@Url.Content(ImagePath)" width="100" class="img-thumbnail" />
                <br>
                @Html.DisplayFor(modelItem => item.HinhAnh)
            </td>
            <td>
                @Html.ActionLink("Sửa", "Edit", new { id = item.MaSanPham }, htmlAttributes: new { @class = "btn btn-info btn-sm" })
                @Html.ActionLink("Chi tiết", "Details", new { id = item.MaSanPham }, htmlAttributes: new { @class = "btn btn-success btn-sm" })
                @Html.ActionLink("Xóa", "Delete", new { id = item.MaSanPham }, htmlAttributes: new { @class = "btn btn-danger btn-sm" })
            </td>
        </tr>
    }

</table>


<div align="center">
    Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("Index",
    new { page }))
</div>