BTL/Controllers/Admin/LoaiSanPhamAdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BTL.Models;
using PagedList;

namespace BTL.Controllers.Admin
{
    public class LoaiSanPhamAdminController : Controller
    {
        private ShopDienThoaiContext db = new ShopDienThoaiContext();

        // GET: LoaiSanPhams
        public ActionResult Index(int? page)
        {
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(db.LoaiSanPhams.OrderBy(h => h.MaLoaiSanPham).ToPagedList(pageNumber, pageSize));
        }

        // GET: LoaiSanPhams/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LoaiSanPham loaiSanPham = db.LoaiSanPhams.Find(id);
            if (loaiSanPham == null)
            {
                return HttpNotFound();
            }
            return View(loaiSanPham);
        }

        // GET: LoaiSanPhams/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: LoaiSanPhams/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaLoaiSanPham,TenLoaiSanPham,HinhAnh")] LoaiSanPham loaiSanPham)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    loaiSanPham.HinhAnh = "";
                    var f = Request.Files["ImageFile"];
                    if (f != null && f.ContentLength > 0)
                    {
                        string FileName = System.IO.Path.GetFileName(f.FileName);
                        string UploadFile = Server.MapPath("~/wwwroot/images/loaisanpham/" + FileName);
                        f.SaveAs(UploadFile);
                        loaiSanPham.HinhAnh = FileName;
                    }
                    db.LoaiSanPhams.Add(loaiSanPham);
                    db.SaveChanges();

                }
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Error = "Lỗi không tạo được ." + ex.Message;
                return View(loaiSanPham);
            }



        }

        // GET: LoaiSanPhams/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LoaiSanPham loaiSanPham = db.LoaiSanPhams.Find(id);
            if (loaiSanPham == null)
            {
                return HttpNotFound();
            }
            return View(loaiSanPham);
        }

        // POST: LoaiSanPhams/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaLoaiSanPham,TenLoaiSanPham,HinhAnh")] LoaiSanPham loaiSanPham)
        {
            try
            {
                LoaiSanPham sp = db.LoaiSanPhams.Find(loaiSanPham.MaLoaiSanPham);
                if (ModelState.IsValid)
                {
                    var f = Request.Files["ImageFile"];
                    if (f != null && f.ContentLength > 0)
                    {
                        string FileName = System.IO.Path.GetFileName(f.FileName);
                        string UploadFile = Server.MapPath("~/wwwroot/images/loaisanpham/" + FileName);
                        f.SaveAs(UploadFile);
                        loaiSanPham.HinhAnh = FileName;
                    }
                    else
                    {
                        loaiSanPham.HinhAnh = sp.HinhAnh;
                    }

                    db.Entry(loaiSanPham).State = EntityState.Modified;
                    db.SaveChanges();

                }
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Error = "Lỗi không sửa được ." + ex.Message;
                return View(loaiSanPham);
            }


        }

        // GET: LoaiSanPhams/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LoaiSanPham loaiSanPham = db.LoaiSanPhams.Find(id);
            if (loaiSanPham == null)
            {
                return HttpNotFound();
            }
            return View(loaiSanPham);
        }

        // POST: LoaiSanPhams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            LoaiSanPham loaiSanPham = db.LoaiSanPhams.Find(id);
            try
            {
                db.LoaiSanPhams.Remove(loaiSanPham);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {

                ViewBag.Error = "Lỗi không sửa được ." + ex.Message;
                return View("Delete", loaiSanPham);
            }

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BTL/Views/LoaiSanPhamAdmin/Create.cshtml
@model BTL.Models.LoaiSanPham

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@using (Html.BeginForm("Create", "LoaiSanPhamAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />

        <div class="form-group">
            <div>Tên Loại Sản Phẩm</div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenLoaiSanPham)
                @Html.ValidationMessageFor(model => model.TenLoaiSanPham, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div>Hình Ảnh</div>
            <div class="col-md-10">
                <img id="output" class="img-rounded" alt="Ảnh" width="180" height="200" src="~/wwwroot/images/261324070_4347523358690584_3346044899357033616_n.png" />
                <p><label for="ufile" style="cursor:pointer" ;>Chọn File Ảnh</label></p>
                <input name="ImageFile" id="ufile" type="file" style="display:none" onchange="loadFile(event)" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" style="border-radius:8px;" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay lại", "Index")
</div>
@if (ViewBag.Error != null)
{
    <br />
    <div class="alert alert-danger" role="alert">@ViewBag.Error</div>
}

<script>
    var loadFile = function(event)
    {
          var image = document.getElementById('output');
        image.src = URL.createObjectURL(event.target.files[0]);
    }

</script>

BTL/Views/LoaiSanPhamAdmin/Delete.cshtml
@model BTL.Models.LoaiSanPham

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}



<h3>Bạn có chắc chắn muốn xóa?</h3>
<div>
    <hr />
    <table style="border:medium">
        <tr>
            <th>Tên loại sản phẩm</th>
        </tr>
        <tr>
            <td> @Html.DisplayFor(model => model.TenLoaiSanPham)</td>
        </tr>
        <tr>
            <th>Hình ảnh</th>
        </tr>
        <tr>
            <td>
                @{
                    string ImagePath = "~/wwwroot/images/loaisanpham/" + Model.HinhAnh;
                }
                <img src="@Url.Content(ImagePath)" width="100" class="img-thumbnail" />
                <br />
                @Html.DisplayFor(model => model.HinhAnh)
            </td>
        </tr>
    </table>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" style="border-radius:8px" /> |
            @Html.ActionLink("Quay lại", "Index")
        </div>
    }
</div>
@if (ViewBag.Error != null)
{
    <br />
    <div class="alert alert-danger" role="alert">@ViewBag.Error</div>
}

BTL/Views/LoaiSanPhamAdmin/Details.cshtml
@model BTL.Models.LoaiSanPham

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Details</h2>

<div>
    <h4>LoaiSanPham</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenLoaiSanPham)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenLoaiSanPham)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HinhAnh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HinhAnh)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MaLoaiSanPham }) |
    @Html.ActionLink("Back to List", "Index")
</p>

BTL/Views/LoaiSanPhamAdmin/Edit.cshtml
@model BTL.Models.LoaiSanPham

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    var ImagePath = "~/wwwroot/images/loaisanpham/" + Model.HinhAnh;
}




@using (Html.BeginForm("Edit", "LoaiSanPhamAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4 style="text-align:center">Chỉnh sửa thông tin sản phẩm</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaLoaiSanPham)

        <div class="form-group">
            <div>Tên loại sản phẩm</div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenLoaiSanPham)
                @Html.ValidationMessageFor(model => model.TenLoaiSanPham, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div>Hình ảnh</div>
            <div class="col-md-10">
                <img id="output" class="img-rounded" alt="Ảnh" width="180" height="200" src="@Url.Content(ImagePath)" />
                <p><label for="ufile" style="cursor:pointer" ;>Chọn File Ảnh</label></p>
                <input name="ImageFile" id="ufile" type="file" style="display:none" onchange="loadFile(event)" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" style="border-radius:8px" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay lại", "Index")
</div>
@if (ViewBag.Error != null)
{
    <br />
    <div class="alert alert-danger" role="alert">@ViewBag.Error</div>
}
<script>
    var loadFile = function(event)
    {
        var image = document.getElementById('output');
        image.src = URL.createObjectURL(event.target.files[0]);
    };

</script>

BTL/Views/LoaiSanPhamAdmin/Index.cshtml
@model PagedList.IPagedList<BTL.Models.LoaiSanPham>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

<h2 style="text-align:center">Quản lý loại sản phẩm</h2>

<p>
    @Html.ActionLink("Tạo Mới", "Create", null, htmlAttributes: new { @class = "btn btn-success btn-sm" })
</p>
<table class="table" border="0">
    <tr style="border:1px">
        <th style="border:1px">
            Tên loại sản phẩm
        </th>
        <th style="border:1px">
            Hình ảnh
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr style="border:1px">
            <td>
                @Html.DisplayFor(modelItem => item.TenLoaiSanPham)
            </td>
            <td>
                @{
                    string ImagePath = "~/wwwroot/images/loaisanpham/" + item.HinhAnh;
                }
                <img src="@Url.Content(ImagePath)" width="100" class="img-thumbnail" />
                <br>
                @Html.DisplayFor(modelItem => item.HinhAnh)
            </td>
            <td>
                @Html.ActionLink("Sửa", "Edit", new { id = item.MaLoaiSanPham }, htmlAttributes: new { @class = "btn btn-info btn-sm" })
                @Html.ActionLink("Xóa", "Delete", new { id = item.MaLoaiSanPham }, htmlAttributes: new { @class = "btn btn-danger btn-sm" })
            </td>
        </tr>
    }

</table>

<div align="center">
    Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("Index",
    new { page }))
</div>