BTL/Controllers/Admin/SlideAdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BTL.Models;
using PagedList;

namespace BTL.Controllers.Admin
{
    public class SlideAdminController : Controller
    {
        private ShopDienThoaiContext db = new ShopDienThoaiContext();

        // GET: SlideAdmin
        public ActionResult Index(int? page)
        {
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(db.Slides.OrderBy(h => h.MaSlide).ToPagedList(pageNumber, pageSize));
        }

        // GET: SlideAdmin/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Slide slide = db.Slides.Find(id);
            if (slide == null)
            {
                return HttpNotFound();
            }
            return View(slide);
        }

        // GET: SlideAdmin/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SlideAdmin/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaSlide,TenSlide,HinhAnh,NoiDung,Link,TrangThai")] Slide slide)
        {
            if (ModelState.IsValid)
            {
                slide.HinhAnh = "";
                var f = Request.Files["ImageFile"];
                if (f != null && f.ContentLength > 0)
                {
                    string FileName = System.IO.Path.GetFileName(f.FileName);
                    string UploadFile = Server.MapPath("~/wwwroot/images/slides/" + FileName);
                    f.SaveAs(UploadFile);
                    slide.HinhAnh = FileName;
                }
                db.Slides.Add(slide);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(slide);
        }

        // GET: SlideAdmin/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Slide slide = db.Slides.Find(id);
            if (slide == null)
            {
                return HttpNotFound();
            }
            return View(slide);
        }

        // POST: SlideAdmin/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaSlide,TenSlide,HinhAnh,NoiDung,Link,TrangThai")] Slide slide)
        {
            if (ModelState.IsValid)
            {
                slide.HinhAnh = "";
                var f = Request.Files["ImageFile"];
                if (f != null && f.ContentLength > 0)
                {
                    string FileName = System.IO.Path.GetFileName(f.FileName);
                    string UploadFile = Server.MapPath("~/wwwroot/images/slides/" + FileName);
                    f.SaveAs(UploadFile);
                    slide.HinhAnh = FileName;
                }
                db.Entry(slide).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(slide);
        }

        // GET: SlideAdmin/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Slide slide = db.Slides.Find(id);
            if (slide == null)
            {
                return HttpNotFound();
            }
            return View(slide);
        }

        // POST: SlideAdmin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Slide slide = db.Slides.Find(id);
            db.Slides.Remove(slide);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BTL/Views/SlideAdmin/Create.cshtml
@model BTL.Models.Slide

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "SlideAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Slide</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TenSlide, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenSlide, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenSlide, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div>Hình ảnh</div>
            <div class="col-md-10">
                <img id="output" class="img-rounded" alt="Ảnh" width="180" height="200" src="~/wwwroot/images/261324070_4347523358690584_3346044899357033616_n.png" />
                <p><label for="ufile" style="cursor:pointer;">Chọn File Ảnh</label></p>
                <input name="ImageFile" id="ufile" type="file" style="display:none" onchange="loadFile(event)" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TrangThai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.TrangThai)
                    @Html.ValidationMessageFor(model => model.TrangThai, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Trở lại", "Index")
</div>

@if (ViewBag.Error != null)
{
    <br />
    <div class="alert alert-danger" role="alert">@ViewBag.Error</div>
}

<script>
    var loadFile = function (event) {
        var image = document.getElementById('output');
        image.src = URL.createObjectURL(event.target.files[0]);
    }
</script>

BTL/Views/SlideAdmin/Delete.cshtml
@model BTL.Models.Slide

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Slide</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Tên slide
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenSlide)
        </dd>

        <dt>
            Hình ảnh
        </dt>

        <dd>
            @{
                var ImagePath = "~/wwwroot/images/slides/" + Model.HinhAnh;
            }
            <img id="output" class="img-rounded" alt="Ảnh" width="180" height="200" src="@Url.Content(ImagePath)" /><br />
            @Html.DisplayFor(model => model.HinhAnh)
        </dd>

        <dt>
            Trạng thái
        </dt>

        <dd>
            @if (Model.TrangThai == true)
            {
                <p>Hiển thị</p>
            }
            else
            {
                <p>Ẩn</p>
            }
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-danger btn-sm" /> 
            @Html.ActionLink("Trở lại", "Index", null, htmlAttributes: new { @class = "btn btn-success btn-sm" })
        </div>
    }
</div>

BTL/Views/SlideAdmin/Details.cshtml
@model BTL.Models.Slide

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Chi tiết</h2>

<div>
    <h4>Slide</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Mã slide
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaSlide)
        </dd>

        <dt>
            Tên slide
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenSlide)
        </dd>

        <dt>
            Hình ảnh
        </dt>

        <dd>
            @{
                var ImagePath = "~/wwwroot/images/slides/" + Model.HinhAnh;
            }
            <img id="output" class="img-rounded" alt="Ảnh" width="180" height="200" src="@Url.Content(ImagePath)" /><br />
            @Html.DisplayFor(model => model.HinhAnh)
        </dd>

        <dt>
            Trạng thái
        </dt>

        <dd>
            @if (Model.TrangThai == true)
            {
                <p>Hiển thị</p>
            }
            else
            {
                <p>Ẩn</p>
            }
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Sửa", "Edit", new { id = Model.MaSlide }, htmlAttributes: new { @class = "btn btn-info btn-sm" }) 
    @Html.ActionLink("Trở lại", "Index", null, htmlAttributes: new { @class = "btn btn-success btn-sm" })
</p>

BTL/Views/SlideAdmin/Edit.cshtml
@model BTL.Models.Slide

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Sửa</h2>

@using (Html.BeginForm("Create", "SlideAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Slide</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaSlide)

        <div class="form-group">
            @Html.LabelFor(model => model.TenSlide, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenSlide, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenSlide, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div>Hình ảnh</div>
            <div class="col-md-10">
                <img id="output" class="img-rounded" alt="Ảnh" width="180" height="200" src="~/wwwroot/images/slides/@Model.HinhAnh" />
                <p><label for="ufile" style="cursor:pointer;">Chọn File Ảnh</label></p>
                <input name="ImageFile" id="ufile" type="file" style="display:none" onchange="loadFile(event)" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TrangThai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.TrangThai)
                    @Html.ValidationMessageFor(model => model.TrangThai, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-danger btn-sm" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Trở lại", "Index", null, htmlAttributes: new { @class = "btn btn-success btn-sm" })
</div>

@if (ViewBag.Error != null)
{
    <br />
    <div class="alert alert-danger" role="alert">@ViewBag.Error</div>
}

<script>
    var loadFile = function (event) {
        var image = document.getElementById('output');
        image.src = URL.createObjectURL(event.target.files[0]);
    }
</script>

BTL/Views/SlideAdmin/Index.cshtml
@model PagedList.IPagedList<BTL.Models.Slide>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

<h2>Danh sách slide</h2>

<p>
    @Html.ActionLink("Thêm", "Create", null, htmlAttributes: new { @class = "btn btn-success btn-sm" })
</p>
<table class="table">
    <tr>
        <th>
            Mã Slide
        </th>
        <th>
            Trạng thái
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MaSlide)
            </td>
            <td>
                @if (item.TrangThai == true)
                {
                    <p>Hiển thị</p>
                }
                else
                {
                    <p>Ẩn</p>
                }
            </td>
            <td>
                @Html.ActionLink("Sửa", "Edit", new { id = item.MaSlide }, htmlAttributes: new { @class = "btn btn-info btn-sm" })
                @Html.ActionLink("Chi tiết", "Details", new { id = item.MaSlide }, htmlAttributes: new { @class = "btn btn-success btn-sm" })
                @Html.ActionLink("Xóa", "Delete", new { id = item.MaSlide }, htmlAttributes: new { @class = "btn btn-danger btn-sm" })
            </td>
        </tr>
    }

</table>

<div align="center">
    Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("Index",
    new { page }))
</div>